### PR TITLE
Make the .deb file fully-reproducible

### PR DESCRIPTION
**Pull request by the-sun-will-rise-tomorrow**
- Reset `registrationTime` in the database - as in https://github.com/NixOS/nixpkgs/pull/289840
- Sort names in `nix.tar.xz` as recommended by https://reproducible-builds.org/docs/archives/#file-ordering
- Reset remaining timestamps (of hard links, directories) in tarball
- Always use single-threaded compression for determinism
- Dereference hard links, to amortize for `auto-optimise-store`

With this, `sha256sum "$(nix-build -A deb)"` should now produce `f1a55f1f26c1d9127762e1659c5562bfe3b5bc8745ae2e31c4524f134f70100b  /nix/store/lxl9pazqvbiv70i74rw7gba6437i4mjh-nix-multi-user-2.17.1.deb` for everyone.

### CODE REVIEW

**Comment by the-sun-will-rise-tomorrow** [comment]
@adisbladis Hi, have you had a chance to look at this?

**Comment by the-sun-will-rise-tomorrow** [comment]
@Mic92 Hi, since this project's maintainer is away, do you know who could look at this?

**Comment by Mic92** [comment]
What happens if you do not dereference hard links?

**Comment by the-sun-will-rise-tomorrow** [comment]
They will be saved to the tar balls as hard links. This causes the output to be different depending on whether `auto-optimise-store` is enabled or not.

See also: https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20hard-dereference&type=code

**Pull request merged**
