### PR TITLE
fix: make nix work out of the box on rpm-ostree

### PR DESCRIPTION
**Pull request by yajo**
The main difference is that restorecon is executed against `/var/nix` instead of against `/nix`, because that's the path that actually exists at that point.

To make it work, SELinux policies are duplicated for the `/var/nix` prefix.

From there onwards, no more recursive restorecon calls are needed.

Also fixed a bug in the start conditions for the socket.

@moduon MT-83

---

I know you closed #5 but I hope you can reconsider it now that, with this patch, all works out of the box.

All you need to do is build it, and then `rpm-ostree install --reboot ./nix.rpm`. Then, after reboot: `systemctl enable --now nix-daemon`.

### CODE REVIEW

**Comment by yajo** [comment]
Booting still warns with:

```
abr 25 11:32:54 yajolap systemd[1]: nix-daemon.socket: Failed to create listening socket (/nix/var/nix/daemon-socket/socket): Permission denied
abr 25 11:32:54 yajolap systemd[1]: nix-daemon.socket: Failed to listen on sockets: Permission denied
abr 25 11:32:54 yajolap systemd[1]: nix-daemon.socket: Failed with result 'resources'.
abr 25 11:32:54 yajolap systemd[1]: Failed to listen on Nix Daemon Socket.
abr 25 11:32:54 yajolap systemd[1]: Starting Nix Daemon...
abr 25 11:32:54 yajolap systemd[1]: Started Nix Daemon.
```

However it seems to work as expected.

Also, since Silverblue is so special, it's not really working after boot. You still need to do:

```
grep -E '^nixbld:' /usr/lib/group | sudo tee -a /etc/group
grep -E '^nixbld.*:' /usr/lib/passwd | sudo tee -a /etc/passwd
systemctl reboot
```

After installing and rebooting.

**Comment by yajo** [comment]
Hmm it still fails weird when I `rpm-ostree update`.

**Comment by yajo** [comment]
Thanks! I really love Fedora Silverblue and nix, and both share similar mindsets, but not being able to mix both was very sad.

I just hope I can get this to a point where I don't sacrifice experience for normal Fedora users. Having a couple extra systemd units shouldn't be a big problem as long as they just work IMHO.

The point of having to add nixbld group and users manually is relatively normal in rpm-ostree world. It's actually [documented](https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group). We would just drop a note in the readme and it should be enough.

Now the biggest problem I have with current code is that it logs this after each boot:

```
abr 26 07:11:44 yajolap systemd[1]: sockets.target: Found ordering cycle on nix-daemon.socket/start
abr 26 07:11:44 yajolap systemd[1]: sockets.target: Found dependency on nix.mount/start
abr 26 07:11:44 yajolap systemd[1]: sockets.target: Found dependency on nix-setup.service/start
abr 26 07:11:44 yajolap systemd[1]: sockets.target: Found dependency on basic.target/start
abr 26 07:11:44 yajolap systemd[1]: sockets.target: Found dependency on sockets.target/start
abr 26 07:11:44 yajolap systemd[1]: sockets.target: Job nix-daemon.socket/start deleted to break ordering cycle starting with sockets.target/start
```

For some weird reason, it thinks that `nix-setup.service` depends on `basic.target`, which itself depends on `sockets.target` and creates a cycle.

My current workaround is to `systemctl disable nix-daemon` and then `systemctl start nix-daemon` manually after each boot. But that's not very elegant.

I've tried several ideas to fix the loop, but none of them worked. Do you have any suggestion?

**Comment by yajo** [comment]
Finally it seems I found how to deal with all corner cases and unit loops. I added to the README specific rpm-ostree instructions. I'm using it right now on my dev PC and works fine. Also tested in a bare-bones Fedora Silverblue VM I've set up. Just follow the instructions and all will go fine.

**Comment by yajo** [comment]
Thanks for your feedback. I rebased and updated the rpm-ostree-specific instructions on the readme to make them more straightforward.

**Comment by jcdickinson** [comment]
Are there any plans to merge this? I am currently using [my rather janky script](https://gitlab.com/jcdickinson/nix/-/blob/main/install-fedora) to get Nix running on my machines, and would like to migrate to this.

**Comment by yajo** [comment]
I've been using this for 2 months on my dev Silverblue machine and it works like a charm. It's up to the maintainer to decide if he wants to merge. On my side AFAIK it's all done.

**Comment by jcdickinson** [comment]
@yajo: I am attempting to bake this into an OSTree. I have found that this is needed in `nix-setup`.

```
+ mkdir -p /var/nix/var/nix/daemon-socket/
+ touch /var/nix/var/nix/daemon-socket/.keep

+ # Set up root channels ()
```

Without that, the `daemon-socket` dir doesn't exist, which fails the prerequisite for the systemd socket.

**Comment by yajo** [comment]
Would you mind to open a PR against my branch?

**Comment by jcdickinson** [comment]
@yajo: https://github.com/moduon/nix-installers/pull/1

**Comment by yajo** [comment]
Hi folks. This has been working without any hassle for some months. Do you think you could merge it?

**Comment by yajo** [comment]
I rebased and rebuilt to include #14 and other changes. Updated zip: [nix-multi-user.rpm.zip](https://github.com/nix-community/nix-installers/files/9940128/nix-multi-user.rpm.zip)

**Comment by dankmemermusic** [comment]
https://gitlab.com/ahayzen/silverblue-nix check this out

**Comment by jcdickinson** [comment]
@dankmemermusic

> We need to disable SELinux otherwise the nix socket cannot be created.

This repo does not have that issue, it creates the required SELinux policies.

**Comment by orowith2os** [comment]
What's the current status of this being merged? If it needs more testing, I can install it locally and see if I can find any issues.

**Comment by orowith2os** [comment]
Hm, found a weird issue.

If I run my rpm-ostree config without this installer, it works just fine. However, the moment I install it, my terminal apps don't launch, and Firefox's theme resets. Uninstalling this installer fixes all of that. It seems to happen regardless of whether or not the systemd service is going, too.

**Comment by yajo** [comment]
I've been using this package for more than 6 months without an issue.

@orowith2os have you followed instructions in the readme? Those that are added in this PR

**Comment by orowith2os** [comment]
> I've been using this package for more than 6 months without an issue.
> 
> @orowith2os have you followed instructions in the readme? Those that are added in this PR

I did them step-by-step, and still have the issue.

My Firefox theme goes back to light, Nautilus and any terminal apps don't open, and some other (GNOME) apps don't work, like Disks. Are there any logs I should upload?

**Comment by yajo** [comment]
Could you make sure your nix profile is totally empty? I'm thinking that maybe some nix apps are conflicting with usual fedora apps.

Otherwise, you could post your logs for all `*nix*` systemd units. And the same for any other failed units you find when booting with the nix package installed.

**Comment by orowith2os** [comment]
@yajo I haven't installed anything via Nix, only enabled it, so I don't see why anything would conflict.

On the systemd unit topic, any commands I should use to grab the logs?

**Comment by orowith2os** [comment]
okay this is a lil weird

I thought I could get into a terminal using vscode's terminal emulator, but something's weird with dbus, I think, and it gives me "the name is not activatable"

**Comment by yajo** [comment]
Not even after rebooting?

**Comment by maribox** [comment]
I found out that it works when I run bash but in my standard shell zsh it does not work

**Comment by yajo** [comment]
I'm no longer using rpm-ostree systems, and https://github.com/DeterminateSystems/nix-installer supports those, so I have no longer interest in this feature. Closing. You can continue in #22 if you wish.

**Pull request closed without merging**
